'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { ArrowUpRight, CheckCircle2, LoaderCircle } from 'lucide-react';
import {waitlistSchema} from '@/lib/validation';
export default function WaitlistForm(){
 const [token,setToken]=useState('');const [state,setState]=useState<'idle'|'pending'|'success'|'error'>('idle');const [message,setMessage]=useState('');const [errors,setErrors]=useState<Record<string,string[]|undefined>>({});const result=useRef<HTMLDivElement>(null);
 async function loadToken(){try{const response=await fetch('/api/waitlist',{cache:'no-store'});if(!response.ok)throw new Error();const data=await response.json();setToken(data.token);}catch{setMessage('The waitlist is temporarily unavailable. Please reload to try again.');setState('error');}}
 useEffect(()=>{void loadToken();},[]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(state==='pending')return;const form=event.currentTarget;const fields=new FormData(form);const payload={fullName:fields.get('fullName'),email:fields.get('email'),phone:fields.get('phone'),interest:fields.get('interest'),location:fields.get('location'),consent:fields.get('consent')==='on',website:fields.get('website'),token};const checked=waitlistSchema.safeParse(payload);
 if(!checked.success){setErrors(checked.error.flatten().fieldErrors);setMessage('Please check the highlighted fields.');setState('error');const first=checked.error.issues[0]?.path[0];
 if(first)form.querySelector<HTMLElement>(`[name="${String(first)}"]`)?.focus();return;}
 setErrors({});setState('pending');setMessage('Saving your place…');
 try{const response=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(checked.data),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok){setErrors(data.errors||{});throw new Error(data.message||'We could not save your request. Please try again.');}setMessage(data.message);setState('success');form.reset();}catch(error){setMessage(error instanceof Error && error.name!=='TimeoutError'?error.message:'We could not confirm your submission. Please try again; duplicate entries are handled safely.');setState('error');void loadToken();}setTimeout(()=>result.current?.focus(),0);
 }
 const err=(name:string)=>errors[name]?.[0];
 return <form onSubmit={submit} aria-busy={state==='pending'} noValidate>
 {state!=='success' && <><div className="row g-3"><div className="col-12"><label htmlFor="fullName" className="form-label">Full name <span aria-hidden="true">*</span></label><input className={`form-control ${err('fullName')?'is-invalid':''}`} id="fullName" name="fullName" autoComplete="name" required maxLength={100} aria-invalid={!!err('fullName')} aria-describedby={err('fullName')?'fullName-error':undefined}/><div id="fullName-error" className="invalid-feedback">{err('fullName')}</div></div>
 <div className="col-12"><label htmlFor="email" className="form-label">Email address <span aria-hidden="true">*</span></label><input className={`form-control ${err('email')?'is-invalid':''}`} type="email" id="email" name="email" autoComplete="email" required maxLength={254} placeholder="you@example.com" aria-invalid={!!err('email')} aria-describedby={err('email')?'email-error':undefined}/><div id="email-error" className="invalid-feedback">{err('email')}</div></div>
 <div className="col-sm-6"><label htmlFor="phone" className="form-label">Phone number <small>(optional)</small></label><input className={`form-control ${err('phone')?'is-invalid':''}`} id="phone" name="phone" type="tel" autoComplete="tel" maxLength={30} aria-invalid={!!err('phone')} aria-describedby={err('phone')?'phone-error':undefined}/><div id="phone-error" className="invalid-feedback">{err('phone')}</div></div>
 <div className="col-sm-6"><label htmlFor="interest" className="form-label">I’m joining as <span aria-hidden="true">*</span></label><select className={`form-select ${err('interest')?'is-invalid':''}`} id="interest" name="interest" defaultValue="Patient" required aria-invalid={!!err('interest')} aria-describedby={err('interest')?'interest-error':undefined}><option>Patient</option><option>Doctor</option><option>Pharmacy Partner</option></select><div id="interest-error" className="invalid-feedback">{err('interest')}</div></div>
 <div className="col-12"><label htmlFor="location" className="form-label">City or state <small>(optional)</small></label><input className={`form-control ${err('location')?'is-invalid':''}`} id="location" name="location" autoComplete="address-level2" maxLength={100} placeholder="e.g. Surulere, Lagos" aria-invalid={!!err('location')} aria-describedby={err('location')?'location-error':undefined}/><div id="location-error" className="invalid-feedback">{err('location')}</div></div></div>
 <div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div>
 <div className="form-check my-4"><input className="form-check-input" type="checkbox" id="consent" name="consent" required aria-invalid={!!err('consent')} aria-describedby="consent-error"/><label className="form-check-label" htmlFor="consent">I agree to receive SwiftCare launch updates by email and, if provided, phone. I can withdraw my consent at any time. <a href="#privacy">Privacy notice</a>.</label><div className="field-error" id="consent-error">{err('consent')}</div></div>
 <button className="btn btn-primary w-100" disabled={state==='pending'||!token} type="submit">{state==='pending'?<><LoaderCircle className="spin" size={18}/> Joining…</>:<>Join the Waitlist <ArrowUpRight size={19}/></>}</button><p className="form-footnote">Launch updates only. No symptoms or medical history needed.</p></>}
 <div ref={result} tabIndex={-1} role={state==='error'?'alert':'status'} aria-live="polite" className={`form-result ${state==='success'?'success':state==='error'?'error':''}`}>{state==='success'&&<CheckCircle2 size={34}/>}<span>{message}</span></div>
 </form>;
}
